# Generated by Django 4.2.23 on 2025-08-13 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AudioSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lecture_title', models.CharField(default='講演音声', help_text='講演のタイトル', max_length=200)),
                ('audio_file_path', models.CharField(default='audio/lecture.mp3', help_text='音声ファイルのパス（media/からの相対パス）', max_length=500)),
                ('duration', models.FloatField(default=0, help_text='音声ファイルの長さ（秒）')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '音声設定',
                'verbose_name_plural': '音声設定',
            },
        ),
    ]
